version: '3.8'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NEXT_PUBLIC_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${NEXT_PUBLIC_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${NEXT_PUBLIC_MONGO_DB}
    networks:
      - hourglass-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "${NEXT_PUBLIC_MONGO_API_PORT}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - hourglass-network

networks:
  hourglass-network:

volumes:
  mongodb_data: